[package]
name = "firm_delay"
version = "0.4.2"
edition = "2021"
authors = ["Yannick Feld"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_pcg = { version = "0.3.1", features = ["serde1"]}
rand = "0.8.5"
rand_distr = "0.4.3"
serde={version="^1.0.189", features = ["derive"] }
serde_json="^1.0.107"
indicatif="^0.17.7"
clap = {version = "4.4.6", features=["derive", "cargo", "color", "help"]}
rayon="^1.8.0"
sampling = { git = "https://github.com/Pardoxa/sampling.git", rev = "c5dc731ce2b0bb45efe2cec76553e9bdf49cb02d", default-features = false  }